### PR TITLE
#136344171 Change Procfile

### PR DESCRIPTION
**Pull request by jackiewmacharia**
#### What does this PR do?
 Updates Procfile content
 #### Description of Task to be completed?
 Set up Cards For Humanity on Heroku
 #### How should this be manually tested?
 Successful deployment to Heroku on this [link](https://arakari-staging.herokuapp.com).
 #### What are the relevant pivotal tracker stories?
 Feature #136344171

### CODE REVIEW

**Comment by gngchrs** [comment]
@andela-jmacharia the heroku app is still not running

**Comment by jackiewmacharia** [comment]
@gangachris I'm troubleshooting on that.

**Comment by gngchrs** [comment]
Ok. Ping me when you make progress @andela-jmacharia

**Comment by gngchrs** [comment]
We don't need this anymore? Right? @andela-jmacharia

**Comment by jackiewmacharia** [comment]
@gangachris no we don't.

**Pull request closed without merging**
